# Generated by Django 4.2.6 on 2023-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_work_work_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag_1', models.CharField(max_length=50)),
                ('tag_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_4', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_5', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_6', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
