# Generated by Django 4.2.6 on 2023-10-19 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default=datetime.datetime(2023, 10, 19, 16, 21, 1, 134007, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
