# Generated by Django 4.2.6 on 2023-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.CharField(max_length=100)),
                ('column_2', models.CharField(max_length=100)),
                ('column_3', models.CharField(max_length=100)),
                ('column_4', models.CharField(max_length=100)),
                ('column_5', models.CharField(max_length=100)),
                ('column_6', models.CharField(max_length=100)),
            ],
        ),
    ]
