# Generated by Django 4.2.6 on 2023-10-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='column_6',
        ),
    ]
